import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getLocale, getTranslations } from "next-intl/server";

import { Container } from "@/components/layout/Container";
import { LessonBreadcrumbs } from "@/components/lesson-page/LessonBreadcrumbs";
import { LessonOutline } from "@/components/lesson-page/LessonOutline";
import { LessonOutlineSheet } from "@/components/lesson-page/LessonOutlineSheet";
import { LessonPager } from "@/components/lesson-page/LessonPager";
import { TableOfContents } from "@/components/lesson-page/TableOfContents";
import { findLesson } from "@/lib/content/course-navigation";
import {
  getCourse,
  getCourses,
  getLessonContent,
  getLessonHeadings,
} from "@/server/content";

// One page per lesson of every course, generated at build time; other lesson URLs are 404.
// Both segments are generated here ("bottom up"): parent params are passed down only from a layout,
// and [course] is generated by a page.
export async function generateStaticParams() {
  return (await getCourses()).flatMap((course) =>
    course.modules.flatMap((module) =>
      module.lessons.map((lesson) => ({
        course: course.slug,
        lesson: lesson.slug,
      })),
    ),
  );
}

export const dynamicParams = false;

export async function generateMetadata({
  params,
}: PageProps<"/[locale]/courses/[course]/[lesson]">): Promise<Metadata> {
  const { course: courseSlug, lesson: lessonSlug } = await params;
  const [course, locale] = await Promise.all([
    getCourse(courseSlug),
    getLocale(),
  ]);
  const found = course && findLesson(course, lessonSlug);
  if (!course || !found?.current) {
    return {};
  }
  const meta = found.current.lesson.meta[locale];
  return {
    title: `${meta.title} – ${course.meta.title[locale]}`,
    description: meta.description,
  };
}

export default async function LessonPage({
  params,
}: PageProps<"/[locale]/courses/[course]/[lesson]">) {
  const { course: courseSlug, lesson: lessonSlug } = await params;
  const [course, locale, t] = await Promise.all([
    getCourse(courseSlug),
    getLocale(),
    getTranslations("LessonPage"),
  ]);
  const found = course && findLesson(course, lessonSlug);
  if (!course || !found?.current) {
    notFound();
  }

  const [Content, headings] = await Promise.all([
    getLessonContent(course, lessonSlug, locale),
    getLessonHeadings(course, lessonSlug, locale),
  ]);
  if (!Content) {
    notFound();
  }

  const { current, previous, next, total } = found;
  const meta = current.lesson.meta[locale];
  const outline = <LessonOutline course={course} currentSlug={lessonSlug} />;

  return (
    <Container className="py-8 sm:py-12">
      <div className="grid gap-10 lg:grid-cols-[15rem_minmax(0,1fr)] xl:grid-cols-[15rem_minmax(0,1fr)_13rem]">
        {/* Course outline: a sticky sidebar on large screens, a side panel below them. */}
        <aside className="hidden lg:block">
          <nav
            aria-label={t("outline")}
            className="sticky top-24 max-h-[calc(100dvh-7rem)] overflow-y-auto pr-2"
          >
            {outline}
          </nav>
        </aside>

        <div className="flex w-full max-w-3xl min-w-0 flex-col gap-8">
          <header className="flex flex-col gap-4">
            <div className="lg:hidden">
              <LessonOutlineSheet courseTitle={course.meta.title[locale]}>
                {outline}
              </LessonOutlineSheet>
            </div>
            <LessonBreadcrumbs
              courseSlug={course.slug}
              courseTitle={course.meta.title[locale]}
              moduleTitle={current.module.meta.title[locale]}
              lessonTitle={meta.title}
            />
            <p className="text-sm text-muted-foreground">
              {t("lessonOf", { number: current.number, total })} ·{" "}
              {t("minutes", { count: meta.minutes })}
            </p>
            <h1 className="text-4xl font-semibold tracking-tight text-balance sm:text-5xl">
              {meta.title}
            </h1>
            <p className="text-xl text-pretty text-muted-foreground">
              {meta.description}
            </p>
          </header>

          {headings.length > 0 && (
            <details className="rounded-lg border border-border p-4 xl:hidden">
              <summary className="cursor-pointer text-sm font-medium">
                {t("onThisPage")}
              </summary>
              <div className="mt-3">
                <TableOfContents headings={headings} />
              </div>
            </details>
          )}

          <article className="prose prose-lg max-w-none prose-academy">
            <Content />
          </article>

          <LessonPager
            courseSlug={course.slug}
            previous={previous}
            next={next}
          />
        </div>

        {headings.length > 0 && (
          <aside className="hidden xl:block">
            <nav
              aria-label={t("onThisPage")}
              className="sticky top-24 flex flex-col gap-3"
            >
              <span className="text-sm font-medium">{t("onThisPage")}</span>
              <TableOfContents headings={headings} />
            </nav>
          </aside>
        )}
      </div>
    </Container>
  );
}
