import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { hasLocale } from "next-intl";
import { getLocale, getTranslations } from "next-intl/server";

import { Container } from "@/components/layout/Container";
import { CourseFinished } from "@/components/lesson-page/CourseFinished";
import { LessonBreadcrumbs } from "@/components/lesson-page/LessonBreadcrumbs";
import { LessonOutline } from "@/components/lesson-page/LessonOutline";
import { LessonOutlineSheet } from "@/components/lesson-page/LessonOutlineSheet";
import { LessonPager } from "@/components/lesson-page/LessonPager";
import { ModuleQuiz } from "@/components/lesson-page/ModuleQuiz";
import { LessonDone } from "@/components/progress/LessonDone";
import { TableOfContents } from "@/components/lesson-page/TableOfContents";
import { pageMetadata } from "@/i18n/page-metadata";
import { routing } from "@/i18n/routing";
import { findLesson, lessonHref } from "@/lib/content/course-navigation";
import { toQuizQuestions } from "@/lib/content/quiz";
import { LOGIN_ENABLED } from "@/lib/features";
import {
  getCourse,
  getCourses,
  getLessonContent,
  getLessonHeadings,
} from "@/server/content";

// One page per lesson of every course and language, generated at build time; other lesson URLs are 404.
// [locale] comes from the layout. [course] is generated here too: parent params are passed down only
// from a layout, and [course] is generated by a page.
export async function generateStaticParams({
  params,
}: {
  params: { locale: string };
}) {
  if (!hasLocale(routing.locales, params.locale)) {
    return [];
  }
  const locale = params.locale;
  return (await getCourses()).flatMap((course) =>
    course.modules.flatMap((module) =>
      module.lessons.map((lesson) => ({
        course: course.slugs[locale],
        lesson: lesson.slugs[locale],
      })),
    ),
  );
}

export const dynamicParams = false;

export async function generateMetadata({
  params,
}: PageProps<"/[locale]/courses/[course]/[lesson]">): Promise<Metadata> {
  const { course: courseSlug, lesson: lessonSlug } = await params;
  const locale = await getLocale();
  const course = await getCourse(courseSlug, locale);
  const lesson =
    course && findLesson(course, lessonSlug, locale)?.current?.lesson;
  if (!course || !lesson) {
    return {};
  }
  const meta = lesson.meta[locale];
  return pageMetadata({
    locale,
    title: `${meta.title} – ${course.meta.title[locale]}`,
    description: meta.description,
    hrefFor: (other) => lessonHref(course, lesson, other),
    type: "article",
  });
}

export default async function LessonPage({
  params,
}: PageProps<"/[locale]/courses/[course]/[lesson]">) {
  const { course: courseSlug, lesson: lessonSlug } = await params;
  const locale = await getLocale();
  const [course, t] = await Promise.all([
    getCourse(courseSlug, locale),
    getTranslations("LessonPage"),
  ]);
  const found = course && findLesson(course, lessonSlug, locale);
  if (!course || !found?.current) {
    notFound();
  }

  // From here on the lesson is identified by its file name, the same in every language.
  const { slug } = found.current.lesson;
  const [Content, headings] = await Promise.all([
    getLessonContent(course, slug, locale),
    getLessonHeadings(course, slug, locale),
  ]);
  if (!Content) {
    notFound();
  }

  const { current, previous, next, total } = found;
  // After the last lesson: the next course on the recommended main path, if there is one.
  const step = course.meta.path;
  const nextCourse =
    next === undefined && step !== undefined
      ? (await getCourses()).find((other) => other.meta.path === step + 1)
      : undefined;
  const meta = current.lesson.meta[locale];
  // The module's quiz comes after its last lesson.
  const quiz =
    current.module.lessons.at(-1) === current.lesson
      ? current.module.quiz
      : undefined;
  const outline = <LessonOutline course={course} currentSlug={slug} />;

  return (
    <Container className="py-8 sm:py-12">
      <div className="grid gap-10 lg:grid-cols-[15rem_minmax(0,1fr)] xl:grid-cols-[15rem_minmax(0,1fr)_13rem]">
        {/* Course outline: a sticky sidebar on large screens, a side panel below them. */}
        <aside className="hidden lg:block">
          <nav
            aria-label={t("outline")}
            className="sticky top-24 max-h-[calc(100dvh-7rem)] overflow-y-auto pr-2"
          >
            {outline}
          </nav>
        </aside>

        <div className="flex w-full max-w-3xl min-w-0 flex-col gap-8">
          <header className="flex flex-col gap-4">
            <div className="lg:hidden">
              <LessonOutlineSheet courseTitle={course.meta.title[locale]}>
                {outline}
              </LessonOutlineSheet>
            </div>
            <LessonBreadcrumbs
              courseSlug={course.slugs[locale]}
              courseTitle={course.meta.title[locale]}
              moduleTitle={current.module.meta.title[locale]}
              lessonTitle={meta.title}
            />
            <p className="text-sm text-muted-foreground">
              {t("lessonOf", { number: current.number, total })} ·{" "}
              {t("minutes", { count: meta.minutes })}
            </p>
            <h1 className="text-4xl font-semibold tracking-tight text-balance sm:text-5xl">
              {meta.title}
            </h1>
            <p className="text-xl text-pretty text-muted-foreground">
              {meta.description}
            </p>
          </header>

          {headings.length > 0 && (
            <details className="rounded-lg border border-border p-4 xl:hidden">
              <summary className="cursor-pointer text-sm font-medium">
                {t("onThisPage")}
              </summary>
              <div className="mt-3">
                <TableOfContents headings={headings} />
              </div>
            </details>
          )}

          <article className="prose prose-lg max-w-none prose-academy">
            <Content />
          </article>

          {/* With a quiz, the lesson is done by taking it – so the "Done" box comes after it. */}
          {LOGIN_ENABLED && !quiz && (
            <LessonDone course={course.slug} lesson={slug} />
          )}

          {quiz && (
            <ModuleQuiz
              course={course.slug}
              module={current.module.slug}
              lesson={slug}
              moduleTitle={current.module.meta.title[locale]}
              questions={toQuizQuestions(quiz, locale)}
            />
          )}

          {LOGIN_ENABLED && quiz && (
            <LessonDone
              course={course.slug}
              lesson={slug}
              quizModule={current.module.slug}
            />
          )}

          {next === undefined && (
            <CourseFinished course={course} nextCourse={nextCourse} />
          )}

          <LessonPager course={course} previous={previous} next={next} />
        </div>

        {headings.length > 0 && (
          <aside className="hidden xl:block">
            <nav
              aria-label={t("onThisPage")}
              className="sticky top-24 flex flex-col gap-3"
            >
              <span className="text-sm font-medium">{t("onThisPage")}</span>
              <TableOfContents headings={headings} />
            </nav>
          </aside>
        )}
      </div>
    </Container>
  );
}
