import "server-only";

import { existsSync } from "node:fs";
import path from "node:path";
import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";

import { databaseUrl } from ".";

// SQL migrations generated by `yarn db:generate`; copied into the Docker image next to server.js.
const MIGRATIONS = path.join(process.cwd(), "drizzle");

/**
 * Brings the database up to date with the migrations in drizzle/. Each migration runs once; the
 * database remembers which ones it has (table drizzle.__drizzle_migrations).
 */
export async function runMigrations() {
  if (!existsSync(path.join(MIGRATIONS, "meta", "_journal.json"))) {
    console.info("[db] no migrations yet – nothing to apply");
    return;
  }
  // A separate single connection, closed when done – the app's pool is not touched.
  const client = postgres(databaseUrl(), { max: 1 });
  try {
    await migrate(drizzle({ client }), { migrationsFolder: MIGRATIONS });
    console.info("[db] migrations applied");
  } finally {
    await client.end();
  }
}
